index:
  path: ""
  controller: MainController
  repository: ""
user:
  path: "user"
  controller: UserController
  repository: UserRepository
images:
  path: "images"
  controller: ImagesController
  repository: ImagesRepository